### ISSUE TITLE
Vendor DIR in .gitignore

### ISSUE THREAD

**Issue by pschilly** [ashkan90/Laravel-Vue-Scaffold#1]
Hello,

This repo cannot be used as directed in the instructions due to the "vendor" directory being in the .gitignore.

Easily correctable but for those who are following the instructions to a "T" it will not work and will throw errors such as: PHP Warning:  require(C:\code\crm/vendor/autoload.php): failed to open stream: No such file or directory in C:\code\crm\artisan on line 18.

Cheers

**Comment by ashkan90** [comment]
You're welcome, I've fixed all problems about server. 
in general I changed the project's all features almost. 

Vue-cli added it's more powerful and flexible than webpack version. You can try it now
